plugins {
    id 'com.android.application'
}
// apply plugin: 'stringfog'

// import com.github.megatronking.stringfog.plugin.kg.RandomKeyGenerator
// import com.github.megatronking.stringfog.plugin.StringFogMode

// stringfog {
//     implementation 'com.github.megatronking.stringfog.xor.StringFogImpl'
//     packageName 'com.github.megatronking.stringfog'
//     enable true
//     kg new RandomKeyGenerator()
//     mode StringFogMode.base64
// }

android {
    namespace="com.github.megatronking.stringfog"
    compileSdk=35
    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        applicationId="com.github.megatronking.stringfog"
        minSdk=21
        targetSdk=35
        versionCode=1
        versionName="1.0"
        testInstrumentationRunner='androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        debug {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
//    implementation 'com.github.megatronking.stringfog:xor:5.0.0'
    testImplementation 'junit:junit:4.13.2'
}
